FROM julia:1.10

WORKDIR /app

COPY Project.toml Manifest.toml ./
RUN julia --project -e 'using Pkg; Pkg.instantiate()'

COPY src/ src/
COPY test/ test/

CMD ["julia", "--project", "-e", "using Pkg; Pkg.test()"]
